### ISSUE TITLE
Search API configurations are not in action

### ISSUE THREAD

**Issue by hkir-dev** [OBASKTools/ontology-search#10]
In the demo pipeline (https://github.com/hkir-dev/obask_demo_pipeline) search api ([solr](https://github.com/OBASKTools/pipeline-updatesolr)?) is not configured properly. When order of the search terms change (), it produces different results and sometimes providing no results.

Some problematic cases:

- When searched `kidney`, `kidney lipoma`(MONDO_0000968) is the first result. But when searched for `kidney lipoma`, MONDO_0000968 is not showing up

**Comment by ubyndr** [comment]
I'd re-run the demo pipeline, and it worked as intended. Additionally, I ran regression tests for CAP, organism, organ, and disease fields, and all tests passed without any issues. cc @dosumis @hkir-dev
